apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: veenagarag/my-locust-image
        command: ["locust", "-f", "/locustfile.py", "--host", "http://192.168.49.2:30533"]
